SELECT ORIGIN.ID, ORIGIN.GENOTYPE, CLONE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ORIGIN
JOIN ECOLI_DATA AS CLONE ON ORIGIN.PARENT_ID = CLONE.ID
WHERE ORIGIN.GENOTYPE & CLONE.GENOTYPE = CLONE.GENOTYPE
ORDER BY ORIGIN.ID;